# Generated by Django 4.2.6 on 2023-10-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesetting',
            options={'ordering': ('name',), 'verbose_name': 'Image Setting', 'verbose_name_plural': 'Image Settings'},
        ),
    ]
