# Generated by Django 4.2.6 on 2023-10-14 19:08

from django.db import migrations, models
import resume.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default='', storage=resume.custom_storages.DocumentStorage(), upload_to='', verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', storage=resume.custom_storages.ImageSettingStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
